name: prayer_times_app
description: "تطبيق أوقات الأذان مع إشعارات وأذكار"
publish_to: 'none' # لا يتم النشر على pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # الحزم الرئيسية
  provider: ^6.1.5
  adhan_dart: ^1.1.2
  intl: ^0.20.2
  jhijri: ^1.0.0
  flutter_local_notifications: ^19.4.0
  file_picker: ^10.3.1
  audioplayers: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
