name: photo
description: تطبيق التقاط الصور واستخراج الأرقام
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # لإدارة الحالة
  provider: ^6.1.5
  image_picker: ^0.8.7+6
  google_mlkit_text_recognition: ^0.15.0
  uuid: ^4.5.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path: ^1.9.0
  path_provider: ^2.0.14
  permission_handler: ^12.0.1
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
