name: prayer_times_app
description: "تطبيق أوقات الأذان مع إشعارات وأذكار"
publish_to: 'none' # لا يتم النشر على pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  adhan_dart: ^1.1.2
  intl: ^0.18.1
  hijri_converter: ^2.0.3
  flutter_local_notifications: ^13.0.0
  file_picker: ^5.2.5
  audioplayers: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
