name: adan
description: تطبيق أوقات الأذن
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5
  adhan_dart: ^1.1.2
  intl: ^0.20.2
  jhijri: ^1.0.0
  flutter_local_notifications: ^19.4.0
  file_picker: ^10.3.1
  audioplayers: ^6.5.0
  flutter_analog_clock: ^1.0.3
  google_fonts: ^6.2.1
  geolocator: ^13.0.1
  shared_preferences: ^2.3.2
  flutter_native_timezone: ^2.0.0
  timezone: ^0.10.1   # لحلّ أخطاء tz

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
